### ISSUE TITLE
marker-utils.ts:24 Uncaught TypeError: Cannot read properties of undefined (reading 'AdvancedMarkerElement')

### ISSUE THREAD

**Issue by cyberprophet** [googlemaps/js-markerclusterer#618] opened 2023-05-18 13:20 UTC
![20230518_221650](https://github.com/googlemaps/js-markerclusterer/assets/48705422/833a554f-4fa6-4f2a-8dcc-2aef6bea09ac)

As the Google Maps API version has been updated, the marker functionality is no longer working.

It seems to be an error related to using clustering.

Can you provide any insight into the possible reasons for this issue?

**Comment by wangela** [comment] 2023-05-18 13:21
If you would like to upvote the priority of this issue, please comment below or react with :+1: so we can see what is popular when we triage.
--------

@cyberprophet Thank you for opening this issue. 🙏
Please check out these other resources that might help you get to a resolution in the meantime:

- [Check the issue tracker](https://developers.google.com/maps/support/#issue_tracker) - bugs and feature requests for Google Maps Platform APIs and SDKs
- [Open a support case](https://developers.google.com/maps/support#contact-maps-support) - Get 1:1 support in Cloud Console.
- [Discord](https://discord.gg/fHTDmZe9En) - chat with other developers
- [StackOverflow](http://stackoverflow.com/questions/tagged/google-maps) - use the `google-maps` tag


_This is an automated message, feel free to ignore._

**Comment by cyberprophet** [comment] 2023-05-18 13:36
Uncaught TypeError: Cannot read properties of undefined (reading 'range')
![20230518_223256](https://github.com/googlemaps/js-markerclusterer/assets/48705422/02c093a1-ddf9-42b4-a231-de4af9c52972)

**Comment by cyberprophet** [comment] 2023-05-18 13:42
![20230518_223754](https://github.com/googlemaps/js-markerclusterer/assets/48705422/dd5401a8-2f59-484c-8ad3-447c27cdec3f)
![20230518_224155](https://github.com/googlemaps/js-markerclusterer/assets/48705422/03d9a91c-b52e-4d09-a4e2-dac2da63e837)
![20230518_224204](https://github.com/googlemaps/js-markerclusterer/assets/48705422/9b32ca85-fa5f-403f-bfc3-8df26934c12f)

**Comment by cyberprophet** [comment] 2023-05-18 13:43
![20230518_223754](https://github.com/googlemaps/js-markerclusterer/assets/48705422/b246ddd6-fdd9-45b4-b068-909528926560)

**Comment by steadyaero** [comment] 2023-05-18 13:57
#617 see related

**Comment by amuramoto** [comment] 2023-05-18 16:40
Closing this as duplicate of https://github.com/googlemaps/js-markerclusterer/issues/617

**Closed by amuramoto** 2023-05-18 16:40 UTC
Labels: type: bug, triage me
