### ISSUE TITLE
mouseover/mouseout per cluster marker

### ISSUE THREAD

**Issue by danielgindi** [googlemaps/js-markerclusterer#160] opened 2021-12-23 10:33 UTC
Thanks for stopping by to let us know something could be better!

 **Is your feature request related to a problem? Please describe.**
In the old marker clusterer, we could have add mouseover/mouseout listeners to the cluster markerer, and that would fire the corresponding events for each cluster marker.  
The new implementation lacks this feature.

 **Describe the solution you'd like**
`MarkerClustererEvents.CLUSTER_MOUSE_OVER`/`MarkerClustererEvents.CLUSTER_MOUSE_OUT` would be great.

 **Describe alternatives you've considered**
Accessing the "protected" `clusters` property.
```js
markerCluster.addListener(markerCluster, MarkerClustererEvents.CLUSTERING_END, () => {
     for (let cluster of markerCluster.clusters) { 
        cluster.marker.addListener('mouseover', () => onClusterMouseOver(cluster));
        cluster.marker.addListener('mouseout', () => onClusterMouseOut(cluster));
     }
 });
```

**Comment by jpoehnelt** [comment] 2021-12-23 16:40
duplicate of #143

**Closed by jpoehnelt** 2021-12-23 16:40 UTC
Labels: type: feature request, triage me

**Comment by danielgindi** [comment] 2021-12-24 05:55
I disagree with the proposed solution in the "duplicate".
You cannot always count on the renderer. I.e if you use a renderer module from npm.
Of course you could "proxy" it, but that is a weird workaround, while for good practices you might want to look at it as an event, and not as a weird workaround.
