### ISSUE TITLE
MarkerClustererOptions - minimumClusterSize

### ISSUE THREAD

**Issue by default-kaas** [googlemaps/js-markerclusterer#282] opened 2022-04-06 14:13 UTC
**Is your feature request related to a problem? Please describe.**
Apparently it is recommended to move from js-markerclustererplus to js-markerclusterer. The problem that I am running into is that minimumClusterSize seems to be missing as a cluster option.

[js-markerclustererplus repository](https://github.com/googlemaps/js-markerclustererplus/blob/main/src/cluster.ts#L160)

 **Describe the solution you'd like**
Could be possible to add to the MarkerClustererOptions the option to add an minimumClusterSize.

 **Additional context**
If there is an alternative solution, I am also fine with that. Could you give me some recommendations?

**Comment by jpoehnelt** [comment] 2022-04-06 14:14
@default-kaas Please take a moment to fill out [this short survey](https://forms.gle/wYuzN6UibnFj7ZL29). Thank you!

_This is an automated message, feel free to ignore._

**Comment by thexs-dev** [comment] 2022-04-07 13:47
I haven't tried yet, but refer to [this comment](https://github.com/googlemaps/js-markerclusterer/issues/111#issuecomment-974368300) on a similar question in case it helps you

**Comment by jpoehnelt** [comment] 2022-04-07 16:54
Seems like a duplicate of #111.

**Closed by jpoehnelt** 2022-04-07 16:54 UTC
Labels: type: feature request, triage me

**Comment by default-kaas** [comment] 2022-04-07 17:25
> I haven't tried yet, but refer to [this comment](https://github.com/googlemaps/js-markerclusterer/issues/111#issuecomment-974368300) on a similar question in case it helps you

Thank you, I will be looking into it.

**Comment by arnaudambro** [comment] 2023-08-26 19:14
because it's simpler if the answer is also here:

```
import {MarkerClusterer, SuperClusterAlgorithm} from '@googlemaps/markerclusterer';

new MarkerClusterer({
  algorithm: new SuperClusterAlgorithm({minPoints: 1234}),
})
```
